### ISSUE TITLE
Unable to resolve "../../example/node_modules/nativewind"

### ISSUE THREAD

**Issue by kratos-respawned** [sidghimire/sidcn#1]
After completing the initial setup as described in docs(Expo), the application throws the following error 
```error
Unable to resolve "../../example/node_modules/nativewind" from "node_modules\sidcn\src\theme\toggleTheme.tsx"
```

**Comment by sidghimire** [comment]
Minor Scripting Error from my side
I have fixed it now. Go forward and install sidcn again and things should be working as expected.
Fixed it just now in a new version sidcn@1.0.8

You can do this and everything should be working fine
**yarn add sidcn**
