### ISSUE TITLE
Why not partner on another project with similar goals ?

### ISSUE THREAD

**Issue by eznix86** [sidghimire/sidcn#3]
This project has the exact same goal as you, it is a bit far ahead.

https://github.com/mrzachnugent/react-native-reusables

**Comment by sidghimire** [comment]
Yeah, I understand, although the takes and objectives are similar, I have a plan of pivoting this project a little differently. The goal is not just to replicate Shadcn. My core idea i want to implement in one stop solution for reanimated ui components.
